## Ejercicios de Matrices

In [3]:
import numpy as np

**Ejercicio 1**: Investigar y ejemplificar diferencias entre np.array y np.matrix

* **np.mat**. Este tipo de estructura solo admite la creación de matrices de dos dimensiones.
* **np.array**. Por otro lado y a diferencia de np.mat, con array se pueden crear estructuras de N dimensiones.

En ambos casos, tanto los objetos matriz como arrays utilizan el argumento .T para devolver la Transpuesta, pero hay algunos elementos agregados con los que cuenta los objetos matrix, poseen .H para la Transpuesta conjugada, y .I para la inversa.

Por otro lado una de las ventajas de los arrays es que son más generales que los objetos matriz. ¿Que pasaría si se quisiera implementar una matriz de tres o cuatro dimensiones? Se utilizaría arrays en lugar de matrices, es por que aprender matrices es mucho más trabajo y se tendría que conocer cada una de sus limitaciones, que son varias en comparación con los arrays.

#### Otras ventajas utilizando arrays

* Muchas funciones de numpy devuelven arrays, no matrices.
* Existe una evidente diferencia en operaciones element-wise y operaciones de algebra lineal.

Algunos ejemplos:

#### Matrix

In [76]:
matrix = np.mat([[25,100],[77,49]])
print(matrix)

mean = matrix.mean(1)
print(mean)

mean.shape
matrix - mean


[[ 25 100]
 [ 77  49]]
[[62.5]
 [63. ]]


matrix([[-37.5,  37.5],
        [ 14. , -14. ]])

#### Arrays

In [78]:
array = np.array([[25,100],[77,49]])
print(array)

mean_a = array.mean(1)
print(mean_a)

mean_a.shape
print(matrix-mean_a)
array - mean_a[:, np.newaxis]


[[ 25 100]
 [ 77  49]]
[62.5 63. ]
[[-37.5  37. ]
 [ 14.5 -14. ]]


array([[-37.5,  37.5],
       [ 14. , -14. ]])

**Ejercicio 2**: Se tiene una red neuronal sencilla (y simplificada) como la de la siguiente imagen:

<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicacion de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producira una nueva matriz con el mismo numero de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la funcion "sigmoid"(descrita a continuacion) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamanio pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la funcion sigmoid. El resultado debe ser un tensor con el mismo numero de filas que la matriz X y una sola columna(una prediccion para cada fila de X

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

In [72]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

def neural_network(X):
    HL1 = [0.25,0.37]
    HL2 = [-8,14]
    H_Layer = np.array([np.dot(X,HL1),np.dot(X,HL2)])
    s = sigmoid(H_Layer)
    OL = [4,9]
    O_Layer = sigmoid(np.dot(s,OL))
    
    return O_Layer

X = np.array([0.50,0.72])

neural_network = neural_network(X)
neural_network

0.999988416671698

**Ejercicio 3**: Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [66]:
def neural_network(X):
    
    HL1 = [0.712,0.112]
    HL2 = [0.355,0.855]
    HL3 = [0.268,0.468]
    
    H_Layer1 = np.dot(X,HL1)
    H_Layer2 = np.dot(X,HL2)
    H_Layer3 = np.dot(X,HL3)
    
    H_Layer = np.array([OL1,OL2,OL3])
    OL = np.array([0.116,0.329,0.708])
    O_Layer = np.dot(H_Layer, OL)    
    
    return O_Layer

X = [1,1]
print (neural_network(X))

X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

print (neural_network(X))

1.014762
1.014762
